# Stale. The application allows closing abandoned issues or pull requests after inactivity.
# It's potentially deprecated, see https://github.com/probot/stale/issues/248.
# Possible alternative is https://github.com/actions/stale.
#
# Installation: https://github.com/apps/stale.
daysUntilStale: 60
daysUntilClose: 7

exemptLabels: [ 'status: pending' ]
exemptProjects: true
exemptMilestones: true
exemptAssignees: true

staleLabel: 'status: stale'

markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further action occurs. Thank you
  for your contributions.

closeComment: false
