linters:
  fast: true
  enable:
    # defaults
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # addition
    - bodyclose
    - exhaustive
    - exportloopref
    - gocritic
    - noctx
