#!/usr/bin/env bash

set -euo pipefail

[ "${BASH_VERSINFO:-0}" -ge 4 ] || {
  echo "bash version 4 or higher is required" >&2
  exit 1
}

declare -A config
config['dryrun']=false

function docs() {
  pushd tools
  trap popd EXIT

  for arg in "${@}"; do
    case "${arg}" in
    install)
      local lock file=package-lock.json
      lock=$(dirname "${file}")/node_modules/checksum.lock
      if [ ! -f "${lock}" ] || [ "$(cat "${lock}")" != "$(md5sum "${file}")" ]; then
        npm ci
        md5sum "${file}" >"${lock}"
      fi
      ;;

    build)
      npx --no-install next build
      ;;

    publish)
      rm -rf ../docs/*
      npx --no-install next export -o ../docs
      rm -f ../docs/README.html # TODO:docs improve configuration
      git checkout ../docs/CNAME ../docs/redirects
      ;;

    start)
      npx --no-install next start
      ;;

    *) break ;;
    esac
  done
}

@debug() { echo "${@}"; }
@trace() { @debug "${@}" && "${@}"; }
@error() { echo "${@}" >&2; }
@fatal() { @error "${@}" && exit 1; }
@usage() {
  cat - <<EOF
Usage: $0 <task> <args>
Tasks:
EOF
  compgen -A function | grep -Ev '^(@|_)' | sort | cat -n
}

@() {
  ${config['dryrun']} && echo "${@}"
  "${@}"
}

_() {
  if ${config['dryrun']}; then
    echo "${@}"
    return
  fi
  trap 'echo "${@}"' ERR
  "${@}"
}

-() {
  if ${config['dryrun']}; then
    echo "${*} || false"
    return
  fi
  trap 'echo "${*} || false"' ERR
  "${@}" || false
}

+() {
  if ${config['dryrun']}; then
    echo "${*} || true"
    return
  fi
  trap 'echo "${*} || true"' ERR
  "${@}" || true
}

function @main() {
  for arg in "${@}"; do
    case "${arg}" in
    -d | --dry-run)
      config['dryrun']=true
      shift
      ;;
    *) break ;;
    esac
  done
  "${@:-@usage}"
}

@main "${@}"
