# [![Quality][quality.icon]][quality.page]
# [quality.page]:     https://sonarcloud.io/summary/new_code?id=octomation_go-module
# [quality.icon]:     https://sonarcloud.io/api/project_badges/measure?project=octomation_go-module&metric=sqale_rating

scan:
  name: Scanning
  runs-on: ubuntu-latest

  steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with: { fetch-depth: 0 }

    - name: Run SonarCloud scanner
      uses: SonarSource/sonarcloud-github-action@v1.9
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  notify:
    name: Notifying
    needs: [ lint, scan, test ]
