daysUntilStale: 30
daysUntilClose: 7

exemptLabels: [ 'status: pending' ]
exemptProjects: true
exemptMilestones: true
exemptAssignees: true

staleLabel: 'status: stale'

markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further action occurs. Thank you
  for your contributions.

closeComment: >
  This issue was closed because it has been stalled for 7 days with no activity.
