name: Define notification message
description: Identify an appropriate notification message.
branding:
  icon: 'message-square'
  color: 'green'
outputs:
  txt:
    description: The message.
    value: ${{ steps.message.outputs.txt }}
runs:
  using: composite
  steps:
    - name: Define notification message
      id: message
      run: |
        if [ '${{ github.event.head_commit.message != null }}' == 'true' ]
        then
          (cat <<-message
        txt=${{ github.event.head_commit.message }}
        message
        ) | head -1 >> $GITHUB_OUTPUT

        elif [ '${{ github.event.inputs.reason != null }}' == 'true' ]
        then
          (cat <<-message
        txt=${{ github.event.inputs.reason }}
        message
        ) | head -1 >> $GITHUB_OUTPUT

        elif [ '${{ github.event.schedule != null }}' == 'true' ]
        then
          echo txt='regular healthcheck' >> $GITHUB_OUTPUT
        else
          echo Cannot define notification message && exit 1
        fi
      shell: bash
